name: C# Build and Test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore GiftAccessoriesManagement/GiftAccessoriesManagement.csproj

      - name: Build project
        run: dotnet build GiftAccessoriesManagement/GiftAccessoriesManagement.csproj --configuration Release --no-restore

      - name: Run tests
        run: dotnet test GiftAccessoriesManagement/GiftAccessoriesManagement.csproj --configuration Release --no-build --verbosity normal

      - name: Check C# code style
        run: |
          dotnet tool update -g dotnet-format || dotnet tool install -g dotnet-format
          ~/.dotnet/tools/dotnet-format GiftAccessoriesManagement/ --verify-no-changes

      - name: Publish project
        run: dotnet publish GiftAccessoriesManagement/GiftAccessoriesManagement.csproj --configuration Release --no-build --output ./publish
